name: ci-nullplatform
env:
  NULLPLATFORM_API_KEY: ${{ secrets.NULLPLATFORM_API_KEY }}
on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install nullplatform cli
        run: curl https://cli.nullplatform.com/install.sh | sh
        
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Start nullplatform CI
        run: np build start
        
      - name: Build asset
        run: |
          docker build -f Dockerfile \
            --build-arg USERNAME_GITHUB=${{ secrets.USERNAME_GITHUB }} \
            --build-arg TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }} \
            -t ${{ github.ref_name }} .
        
      - name: Push asset
        run: np asset push --type docker-image --source ${{ github.ref_name }}
        
      - name: End nullplatform CI
        if: ${{ always() }}
        run: np build update --status ${{ contains(fromJSON('["failure", "cancelled"]'), job.status) && 'failed' || 'successful' }}