name: SonarCloud
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Set Settings.xml
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: '[{"id": "github", "username": "${{ secrets.USERNAME_GITHUB }}", "password": "${{ secrets.TOKEN_GITHUB }}"}]'

      - name: Run SonarCloud analysis
        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} /
        run: mvn clean test package -Pgithub verify sonar:sonar -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }}